In [1]:
from datastore.data import P3B3
from datastore.data import RandomData
from datastore.data import KuzushijiMNIST
from datastore.data import RandomMultiTaskData
from datastore.sampling.bootstrap import bootstrap

from torch.utils.data import DataLoader

In [27]:
# Random Dataset
random_data = RandomData(num_samples=10, num_classes=2, seed=None)
random_samples = bootstrap(random_data, num_bootstraps=2)

In [28]:
def get_dataloaders(split):
    trainloader = DataLoader(split.train, batch_size=1)
    validloader = DataLoader(split.valid, batch_size=1)
    return trainloader, validloader

In [29]:
trainloader, validloader = get_dataloaders(random_samples[0])

In [30]:
def print_data_samples(dataloader):
    print(f'number of samples: {len(dataloader)}')
    for idx, (data, target) in enumerate(dataloader):
        print(data)

In [31]:
print_data_samples(trainloader)

number of samples: 5
tensor([2.1388], dtype=torch.float64)
tensor([0.1293], dtype=torch.float64)
tensor([0.6594], dtype=torch.float64)
tensor([-0.0213], dtype=torch.float64)
tensor([1.3627], dtype=torch.float64)


In [32]:
print_data_samples(validloader)

number of samples: 5
tensor([-0.8641], dtype=torch.float64)
tensor([-0.7178], dtype=torch.float64)
tensor([0.2519], dtype=torch.float64)
tensor([-1.2204], dtype=torch.float64)
tensor([-1.1957], dtype=torch.float64)


In [33]:
trainloader, validloader = get_dataloaders(random_samples[1])

In [34]:
print_data_samples(trainloader)

number of samples: 5
tensor([1.3627], dtype=torch.float64)
tensor([0.6594], dtype=torch.float64)
tensor([-0.0213], dtype=torch.float64)
tensor([2.1388], dtype=torch.float64)
tensor([-0.0213], dtype=torch.float64)


In [35]:
print_data_samples(validloader)

number of samples: 6
tensor([-0.8641], dtype=torch.float64)
tensor([-0.7178], dtype=torch.float64)
tensor([0.2519], dtype=torch.float64)
tensor([-1.2204], dtype=torch.float64)
tensor([-1.1957], dtype=torch.float64)
tensor([0.1293], dtype=torch.float64)
