In [2]:
from datastore.data import P3B3
from datastore.data import RandomData
from datastore.data import KuzushijiMNIST
from datastore.data import RandomMultiTaskData
from datastore.sampling import leave_one_out_bootstrap

from torch.utils.data import DataLoader

In [3]:
# Random Dataset
random_data = RandomData(num_samples=10, num_classes=2, seed=None)
random_samples = leave_one_out_bootstrap(random_data, num_bootstraps=2)

In [4]:
def get_dataloaders(sample):
    trainloader = DataLoader(sample.train, batch_size=1)
    validloader = DataLoader(sample.test, batch_size=1)
    return trainloader, validloader

In [5]:
def get_set(dataloader, verbose=False):
    if verbose:
        print(f'number of samples: {len(dataloader)}')
        
    elems = set()
    for idx, (data, target) in enumerate(dataloader):
        elems.add(data.item())
        
        if verbose:
            print(data)
    
    return elems

In [9]:
def inspect_sample(sample, verbose=False):
    train_loader, valid_loader = get_dataloaders(sample)
    if verbose: print(f'Training set\n')
    train_elems = get_set(train_loader, verbose)
    if verbose: print(f'\nTest set\n')
    valid_elems = get_set(valid_loader, verbose)
    intersection = train_elems.intersection(valid_elems)
    print(f'\nIntersection of training and test sets: {intersection}')

In [10]:
def inspect_all_samples(samples, verbose=False):
    for idx, sample in enumerate(samples):
        print(f'\nSample {idx}')
        inspect_sample(sample, verbose)

In [11]:
inspect_all_samples(random_samples, verbose=True)


Sample 0
Training set

number of samples: 5
tensor([0.7099], dtype=torch.float64)
tensor([-0.7623], dtype=torch.float64)
tensor([-1.0566], dtype=torch.float64)
tensor([-1.0566], dtype=torch.float64)
tensor([0.4909], dtype=torch.float64)

Test set

number of samples: 6
tensor([2.1639], dtype=torch.float64)
tensor([1.7255], dtype=torch.float64)
tensor([-0.1784], dtype=torch.float64)
tensor([-0.1378], dtype=torch.float64)
tensor([-0.5032], dtype=torch.float64)
tensor([0.6769], dtype=torch.float64)

Intersection of training and test sets: set()

Sample 1
Training set

number of samples: 5
tensor([0.7099], dtype=torch.float64)
tensor([1.7255], dtype=torch.float64)
tensor([-0.1378], dtype=torch.float64)
tensor([2.1639], dtype=torch.float64)
tensor([-0.1784], dtype=torch.float64)

Test set

number of samples: 5
tensor([-0.7623], dtype=torch.float64)
tensor([-1.0566], dtype=torch.float64)
tensor([0.4909], dtype=torch.float64)
tensor([-0.5032], dtype=torch.float64)
tensor([0.6769], dtype=torch