In [13]:
from datastore.data import P3B3
from datastore.data import RandomData
from datastore.data import KuzushijiMNIST
from datastore.data import RandomMultiTaskData
from datastore.sampling.bootstrap import bootstrap

from torch.utils.data import DataLoader

In [14]:
# Random Dataset
random_data = RandomData(num_samples=10, num_classes=2)
random_samples = bootstrap(random_data, num_bootstraps=2)

In [15]:
def get_dataloaders(split):
    trainloader = DataLoader(split.train, batch_size=1)
    validloader = DataLoader(split.valid, batch_size=1)
    return trainloader, validloader

In [16]:
trainloader, validloader = get_dataloaders(random_samples[0])

In [17]:
for idx, (data, target) in enumerate(trainloader):
    print(data)

tensor([1.3451], dtype=torch.float64)
tensor([0.5323], dtype=torch.float64)
tensor([0.8612], dtype=torch.float64)
tensor([0.4518], dtype=torch.float64)
tensor([0.5323], dtype=torch.float64)


In [18]:
for idx, (data, target) in enumerate(validloader):
    print(data)

tensor([-0.7124], dtype=torch.float64)
tensor([0.7538], dtype=torch.float64)
tensor([-0.0445], dtype=torch.float64)
tensor([1.3502], dtype=torch.float64)
tensor([1.4787], dtype=torch.float64)
tensor([-1.0454], dtype=torch.float64)
